- name: Playbook
  hosts: all
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure apache is at the latest version
      yum:
        name: httpd
        state: latest
    - name: ensure apache is running
      service:
        name: httpd
        state: started
    - name: copy file
      ansible.builtin.copy:
        src: my-project.txt
        dest: /home/ec2-user/my-project.txt